runtime: nodejs16
env: standard
instance_class: F1
handlers:
    - url: /(.*\.(js|css|svg|png)(|\.map))$
      static_files: build/\1
      upload: build/(.*)(|\.map)
    - url: /.*
      static_files: build/index.html
      upload: build/.*


automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: surya-systems@appspot.gserviceaccount.com
