env: flex
runtime: custom
env_variables:
  NODE_ENV: 'production'
# instance_class: F2
service: default
# inbound_services:
#     - warmup
readiness_check:
  app_start_timeout_sec: 1500
# automatic_scaling:
#   min_num_instances: 1
# manual_scaling:
#   instances: 1
resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 30
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 2.0
handlers:
    - url: /.*
      secure: always
      script: auto