env: flex
# runtime: nodejs
# env_variables:
#   NODE_ENV: 'production'
service: default
# manual_scaling:
#   instances: 1
# inbound_services:
#     - warmup
# # manual_scaling:
# #   instances: 1
# resources:
#   cpu: 2
#   memory_gb: 8.0
#   disk_size_gb: 10
#   volumes:
#   - name: ramdisk1
#     volume_type: tmpfs
#     size_gb: 1.5
# handlers:
#     - url: /.*
#       secure: always
#       script: auto
runtime: custom