runtime: nodejs16
env: standard
instance_class: F1
handlers:
  - url: /.*
    static_files: build/index.html
    upload: build/index.html


automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
service_account: surya-systems@appspot.gserviceaccount.com
