runtime: nodejs16
env: standard
instance_class: F1
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    require_matching_file: false
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    require_matching_file: false
    upload: build/index.html
  - url: .*
    script: auto