steps:
- name: node
  entrypoint: npm
  args: ["install"]
  dir: 'frontend'
- name: node
  entrypoint: npm
  args: ["run", "build"]
  dir: 'frontend'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"

