steps:
    - id: 'yarn install'
      name: node:${_NODE_VERSION}-alpine
      entrypoint: yarn
      args: ['install', '--production']
      dir: 'frontend'

    - id: 'yarn build'
      name: node:${_NODE_VERSION}-alpine
      entrypoint: 'yarn'
      args: ['build', '--production', '--verbose']
      dir: 'frontend'

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'app.yaml']
      dir: 'frontend'
substitutions:
  _NODE_VERSION: '16.13.0'
  _CACHE_BUCKET: ''

timeout: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
