steps:
    - name: 'node:16'
      entrypoint: 'node'
      id: 'node'
      args: ['install', '--production']
      dir: 'frontend'
    - name: 'node:16'
      entrypoint: 'yarn'
      args: ['build', '--production']
      dir: 'frontend'
      waitFor: ['node']
timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY