steps:
    - name: 'node:16'
      entrypoint: 'yarn'
      args: ['install']
      dir: 'frontend'
    - name: 'node:16'
      entrypoint: 'yarn'
      args: ['build']
      dir: 'frontend'
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'app.yaml']
      dir: 'frontend'
timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY