steps:
    - name: 'node'
      entrypoint: 'yarn'
      id: 'yarn'
      args: ['install', '--verbose']
      dir: 'frontend'
    - name: 'node'
      entrypoint: 'yarn'
      args: ['run', 'build']
      dir: 'frontend'
      waitFor: ['yarn']
timeout: '300s'
options:
  logging: CLOUD_LOGGING_ONLY