steps:
    - name: 'node'
      entrypoint: 'yarn'
      args: ['install', '--production', '--verbose']
      dir: 'frontend'
    # - name: 'node:14'
    #   entrypoint: 'yarn'
    #   args: ['build']
    #   dir: 'frontend'
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', 'app.yaml']
      dir: 'frontend'
timeout: '300s'
options:
  logging: CLOUD_LOGGING_ONLY