steps:
    - name: 'node:16'
      entrypoint: 'yarn'
      id: 'yarn'
      args: ['install', '--production', '--verbose']
      dir: 'frontend'
    - name: 'node:14'
      entrypoint: 'yarn'
      args: ['build', '--production']
      dir: 'frontend'
      waitFor: ['yarn']
timeout: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY