steps:
    - name: 'npm'
      entrypoint: 'npm'
      id: 'npm'
      args: ['install', '--production', '--legacy-peer-deps']
      dir: 'frontend'
    - name: 'yarn'
      entrypoint: 'yarn'
      args: ['build', '--production']
      dir: 'frontend'
      waitFor: ['npm']
timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY