steps:
    - name: 'node:${_NODE_VERSION}'
      entrypoint: 'node'
      id: 'node'
      args: ['install', '--${_NODE_ENV}']
      dir: 'frontend'
    - name: 'node:${_NODE_VERSION}'
      entrypoint: 'yarn'
      args: ['build', '--${_NODE_ENV}']
      dir: 'frontend'
      waitFor: ['node']
timeout: '3600s'
substitutions:
  _NODE_VERSION: 16
  _NODE_ENV: production

options:
  logging: CLOUD_LOGGING_ONLY