steps:
    - id: 'npm install'
      name: node:${_NODE_VERSION}-alpine
      env:
        - 'NODE_ENV=production'
      entrypoint: npm
      args: ['install', '--production']
      dir: 'frontend'

    - id: 'yarn build'
      name: node:${_NODE_VERSION}-alpine
      entrypoint: 'yarn'
      args: ['build', '--production', '--verbose']
      dir: 'frontend'

    - id: 'app deploy'
      env:
        - 'NODE_ENV=production'
      name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', '--set-env-vars', 'NODE_ENV=production']
      dir: 'frontend'
substitutions:
  _NODE_VERSION: '16.13.0'

timeout: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'
